### ISSUE TITLE
To pass non-static method of an object to timerAlarm

### ISSUE THREAD

**Issue by alexCajas** [z01ne/MyAlarm#1]
Hi!, good project, I would like to know if it is possible to pass a non-static method of an Object to timerAlarm to use like a callback. Thanks!

**Comment by z01ne** [comment]
Hi, thanks for your interest, yeah for sure, just capture the object in a lambda expression and pass it as a callback
for example:
`FooClass barObject;
void setup(){
timerAlarm.createTimer(0, 0, 5, [barObject](){
barObject.fooFunction();
});
}
void loop(){
timerAlarm.update();
}
`
